### ISSUE TITLE
Add map

### ISSUE THREAD

**Issue by kz-userstat** [kazstat/sdg-site-kazstat#10]

**Comment by brockfanning** [comment]
@Zhanybek Here you can paste the Russian region names with their codes.

**Comment by kz-userstat** [comment]
Finally I found the place where I have to put Russian region names with their codes. I will do it this evening? because information is in my laptop

**Comment by brockfanning** [comment]
@kz-userstat Perfect, thank you.

**Comment by brockfanning** [comment]
Thanks @Zhanybek for compiling the geojson!

@ainurchik A rough draft of a map is up for 1-1-1: https://kazstat.github.io/sdg-site-kazstat/1-1-1/

Click on the "Карта" tab to see the map.

Please pardon my ignorance, I am still unsure about the situation with Южно-Казахстанская and Туркестанская. Are these to be treated as different regions? Right now I'm treating them both with the GeoCode "KZ10", and the map is only displaying Туркестанская.

**Comment by ainurchik** [comment]
Dear Brock, it is ok with maps - before 2018 we had only Южно-Казахстанская region, then it [is divided into 2 regions: Туркестанская and  г.Шымкент....Thus, until 2018, we have 16 regions, starting from 2018 - 17

**Comment by brockfanning** [comment]
@ainurchik Maps have been turned on now for many indicators across the site. A few notes:
* The maps cannot display disaggregation, so they can only display one series per indicator. Some indicators may not be displaying a map, because I do not know which series you would prefer.
    Example: [1-1-1](https://kazstat.github.io/sdg-site-kazstat/ru/1-1-1/) is not displaying a map. In order to display a map there, you would need to decide what series to use. (Such as: 1.9 income + Rural, for example)
* The difference between Южно-Казахстанская and Туркестанская/г.Шымкент has not been implemented yet. This may require changes in Open SDG. For now, the map is displaying Туркестанская/г.Шымкент for all years.

**Comment by brockfanning** [comment]
Closing this initial issue so we can pursue more specific map stuff in new issues.
