### ISSUE TITLE
Update metadata fields in order to create links 

### ISSUE THREAD

**Issue by kz-userstat** [kazstat/sdg-site-kazstat#22]

**Comment by brockfanning** [comment]
@ainurchik Could provide one example to help with this? For any one indicator, what link would you like to appear?

**Comment by ainurchik** [comment]
Sorry, Brock...What link/example you ask? I am not understand your question

**Comment by kz-userstat** [comment]
Брок просит дать пример как будет выглядеть ссылка показателя/индикатора

**Comment by brockfanning** [comment]
No problem - I believe this issue was about getting a **link** into the "National Metadata" for an indicator. I think the purpose was to link to a PDF file?

I was wondering if you could provide one as a specific example. In other words, let me know this info:

* Which indicator?
* What the link should say?
* Where the link should link to?

It's not urgent, but would helpful to me.

**Comment by ainurchik** [comment]
Ok, Brock...I understand and try to provide some example some later, on this weekend

**Comment by brockfanning** [comment]
I will close this for now, and we can open new issues as needed.
